spring:
  application:
    name: uber-commerce


  ai:
    stabilityai:
      api-key: ${SPRINGAI_STABILITYAI_KEY}





logging:
  level:
    org.springframework.web: INFO
    org.springframework.jdbc: INFO

